# Configuration Keys
AMIAMI_OUTPUT_IMAGE_FOLDER = 'AMIAMI_OUTPUT_IMAGE_FOLDER'
COSPA_OUTPUT_IMAGE_FOLDER = 'COSPA_OUTPUT_IMAGE_FOLDER'
GOODSMILE_OUTPUT_IMAGE_FOLDER = 'GOODSMILE_OUTPUT_IMAGE_FOLDER'
IMAGE_DOWNLOAD_LOG_PATH = 'IMAGE_DOWNLOAD_LOG_PATH'
